<a href="https://colab.research.google.com/github/ShubhamS40/MachineLearning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy is
**The short form of numerical python if you create an array**

In [2]:
import numpy as np
import pandas as pd

# create an array using numpy

In [3]:
arr=np.array(["shubham","mansi","golu","sonu"])

In [4]:
arr

array(['shubham', 'mansi', 'golu', 'sonu'], dtype='<U7')

In [5]:
arr[1]

'mansi'

### Random Array Creation using Numpy

In [6]:
empty_array=np.empty([2,3])

In [7]:
empty_array

array([[5.00579155e-310, 0.00000000e+000, 2.12199579e-314],
       [5.73570307e+169, 1.23763682e+224, 1.87277863e+261]])

### using arange function crate an array

In [9]:
new_arr=np.arange(50)

In [10]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
new_arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [19]:
linespace_arr=np.linspace(10,5,12)

In [20]:
linespace_arr


array([10.        ,  9.54545455,  9.09090909,  8.63636364,  8.18181818,
        7.72727273,  7.27272727,  6.81818182,  6.36363636,  5.90909091,
        5.45454545,  5.        ])

In [21]:
new_arr=np.arange(100)

In [29]:
arr=new_arr.reshape(5,20
                )

In [24]:
empty=np.empty((5,2))

In [25]:
empty

array([[5.00579182e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.88383281e-062],
       [3.88586224e-033, 4.26611660e-090],
       [6.17159872e-042, 8.14152038e-315]])

In [26]:
np.shape(empty)

(5, 2)

In [27]:
np.size(empty)

10

In [31]:
np.ndim(empty)

2

In [38]:
dim3=np.array([[[2,4,6],[3,7,8]],[[2,5,6],[2,4,6]]])

# it help to check the number of dimensional array

In [39]:
np.ndim(dim3)

3

In [48]:
name = np.array(["Alice", "Bob"])


In [49]:
print(name.dtype)

<U5


In [51]:
count=np.array([10])

## **it help to convert the data type of an array using astype**

In [53]:
count.astype(float)

array([10.])

## using numpy we used mostly use function

- power
- square
- vstack
- delete
- sort
- ndim
## Note:- Where is mostly used to find the specific element in array

In [54]:
np.sqrt(count)

array([3.16227766])

In [55]:
arr_num=np.array([1,2,3,4,5])

In [57]:
 np.square(arr_num)

array([ 1,  4,  9, 16, 25])

In [61]:
np.vstack(arr_num)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [62]:
np.hstack(arr_num)

array([1, 2, 3, 4, 5])

In [63]:
np.delete(arr_num,2)

array([1, 2, 4, 5])

In [65]:
np.power(arr_num,3)

array([  1,   8,  27,  64, 125])

In [67]:
new_arr=np.arange(100)

In [73]:
arr=np.empty([2,5])

In [74]:
arr

array([[5.00579182e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [5.88383281e-062, 3.88586224e-033, 4.26611660e-090,
        6.17159872e-042, 8.14152038e-315]])

In [75]:
np.sort(arr)

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 5.00579182e-310],
       [8.14152038e-315, 4.26611660e-090, 5.88383281e-062,
        6.17159872e-042, 3.88586224e-033]])

In [76]:
new_arr=np.arange(100)

In [77]:
np.where(new_arr>50)

(array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [78]:
np.max(new_arr)

99

In [80]:
np.sum(new_arr)+100

5050

In [81]:
zeros=np.zeros([2,3])

#using numpy we can create zeros array or identity matrix

In [82]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
arr=np.array([[2,4,6],[4,5,6]])

In [86]:
np.sum(arr,axis=1)

array([12, 15])

In [87]:
np.sum(arr,axis=0)

array([ 6,  9, 12])

In [88]:
a=[10]

In [90]:
type(a)

list

In [94]:
identity_matrix=np.identity(5)

In [95]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
type(arr)

numpy.ndarray

In [92]:
user={
    "name":"shubham"
}

In [93]:
type(user)

dict